### ISSUE TITLE
Best way of constructing objects

### ISSUE THREAD

**Issue by matheusmr13** [terence410/ts-datastore-orm#2]
I came across this problem:
 - Can't create a constructor cause of this error "The 'this' context of type 'typeof MyEntity' is not assignable to method's 'this' of type 'typeof BaseEntity'.ts(2684)"

Should I set all properties as required and set a default empty state (empty string, 0, etc) or set all as nullable (with ?: operator)?

Or am I missing something about typescript? 🤔

**Comment by terence410** [comment]
can you share your script to me?

**Comment by matheusmr13** [comment]
Testing more with this lib I saw `MyEntity.create` and it works fine. But still don't know why can I create a constructor like this:

```typescript
import { BaseEntity, Column, Entity } from "ts-datastore-orm";

@Entity({kind: "test"})
class Test extends BaseEntity {
    @Column({ generateId: true })
    public id: number = 0;
    

	@Column({ index: true })
	public name: string;

	constructor(name: string) {
		super();
		this.name = name;
	}

	static async findFirstTest(name:string) {
		const tests = await Test.query()
			.filter("name", "=", name)
			.run();

		return tests;
	}

	static async buildTest(name:string) {
		const test = new Test(name);
		await test.save();
		return test;
	}
}
export default Test;
```

**Comment by terence410** [comment]
I got what you mean, because after a query, it has to create an instance of the type. But at that instance, it will have no ideas what's the parameter when creating a new type. 

There are two options:
- Give the constructor a default value for the arguments: constructor(name: string = "") 
- Set the default value in the attributes directly public name: string = "";

**Comment by matheusmr13** [comment]
Oh I see. This was just a misconception about typescript indeed, sorry for this issue and thanks for the explanation!

**Comment by terence410** [comment]
please enjoy the package
