### ISSUE TITLE
Firestore?

### ISSUE THREAD

**Issue by jayarjo** [terence410/ts-datastore-orm#5]
I know Google has Datastore and then what they call Firestore. I don't quite understand the difference, but is this library compatible with both?

**Comment by terence410** [comment]
Google rebrand the Firebase and Datastore into "Cloud FireStore". There are two type of settings

FireStore in Native mode
- This is real time database which is useful if you want you client directly accessing the DB with some real time event features.

FireStore in Datastore mode
- This is for server data storage. You can imagine it's MYSQL for PHP. My library if for this mode.
