### ISSUE TITLE
Can we run before hook before generating insert data?

### ISSUE THREAD

**Issue by zhanglid** [terence410/ts-datastore-orm#8]
I have a use case to modify the entity date before insert. For example, generate a createdAt, lastModified. It would be easy for me to use hook to auto modify entity.

https://github.com/terence410/ts-datastore-orm/blob/dee4c7900ffe9e4aae0d18378012d9a3ba934304/src/Repository.ts#L325-L329

**Comment by terence410** [comment]
You are right, that sound like a bug, I will fix it

**Comment by terence410** [comment]
problem solved in v2.0.7

**Comment by zhanglid** [comment]
Thank you!
